apiVersion: v1
kind: Service
metadata:
  labels:
    app: blidane-konga
  name: blidane-konga
  namespace: kong
spec:
  ports:
  - nodePort: 30179
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: blidane-konga
  type: NodePort
